In [1]:
import numpy as np

## array

In [3]:
liste=[10,20,30,40]
print(type(liste))
np.array(liste)

<class 'list'>


array([10, 20, 30, 40])

In [4]:
matrixListe=[[10,20,30],[20,30,40],[30,40,50]]
np.array(matrixListe)

array([[10, 20, 30],
       [20, 30, 40],
       [30, 40, 50]])

## methodlar

##### arange

In [6]:
np.arange(0,10,2) # =range(0,10,2)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### zeros-ones

In [10]:
print(np.zeros(5))
print(np.ones((2,2)))

[0. 0. 0. 0. 0.]
[[1. 1.]
 [1. 1.]]


#### linspace

In [16]:
np.linspace(0,20,15) # 0'la 20 arasında, eşit farklı, 6 adet rakam seçilir.

array([ 0.        ,  1.42857143,  2.85714286,  4.28571429,  5.71428571,
        7.14285714,  8.57142857, 10.        , 11.42857143, 12.85714286,
       14.28571429, 15.71428571, 17.14285714, 18.57142857, 20.        ])

#### eye

In [18]:
np.eye(5) # 5'e 5 matris, diagonal 1 gerisi 0

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

#### random

In [26]:
print(np.random.randn(4)) # standart distribüsyona göre değerler üretir
print(np.random.randn(4,4))
print(np.random.randint(1,10)) # 1 dönebilir 10 dönemez
print(np.random.randint(1,300,5))

[ 0.4932891   2.20923101 -0.01793614 -1.02784392]
[[ 0.213812    0.33284577 -1.40630251 -0.78451957]
 [-2.04661309 -2.07111977  0.03446156  0.17614752]
 [-1.22235207 -0.14651016  0.25528577  0.28159898]
 [-0.6446936  -0.09157889 -0.1714209   0.45849699]]
8
[157 276 222 245  47]


### Dizi metodları

#### reshape

In [33]:
dizi=np.random.randint(0,100,20)
print(dizi)
dizi.reshape(5,4) # sayıların uyuşması gerekir! dizi değişkenini değiştirmez!!!

[27 64 82 96 17 66 22 77 66 44 42  0  8 12 86 70 63 42 43 45]


array([[27, 64, 82, 96],
       [17, 66, 22, 77],
       [66, 44, 42,  0],
       [ 8, 12, 86, 70],
       [63, 42, 43, 45]])

#### max-min / argmax-argmin

In [35]:
print(dizi.max())
print(dizi.argmax()) # max indexi
print(dizi.min())
print(dizi.argmin()) # min indexi

96
3
0
11


## Slicing-Index

In [48]:
dizi=np.arange(0,15)
dizi1=[30,40,50,60,70]
dizi[3:8]=dizi1
print(dizi)
dizi[12:]=-5
print(dizi)

[ 0  1  2 30 40 50 60 70  8  9 10 11 12 13 14]
[ 0  1  2 30 40 50 60 70  8  9 10 11 -5 -5 -5]


In [52]:
ornekDizi = np.arange(0,10) # numpy dizilerinin bir kısma başka diziye aktarılıp
slicingDizi = ornekDizi[5:] # değiştirilirse orjinal dizideki değerler de değişir
slicingDizi[:]=700  # Bunun önüne geçmek için orijinal dizinin .copy fonksiyonuyla
ornekDizi           #kopyası alınır ve bunun üzerinden işlemler yapılır

array([  0,   1,   2,   3,   4, 700, 700, 700, 700, 700])

In [54]:
yeniListe= [[0,1,2],[3,4,5],[6,7,8],[9,10,11]]
yeniMatrix=np.array(yeniListe)
yeniMatrix[2:,1]

array([ 7, 10])

In [56]:
yeniMatrix[[3,0,2]]

array([[ 9, 10, 11],
       [ 0,  1,  2],
       [ 6,  7,  8]])

## Operasyonlar

In [60]:
liste= np.random.randint(1,100,20)
liste

array([68, 98, 17, 37, 52, 73, 58, 57, 18, 80, 73, 99, 89, 16, 85, 57, 71,
       99, 66, 56])

In [61]:
liste>25

array([ True,  True, False,  True,  True,  True,  True,  True, False,
        True,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True])

In [65]:
sonListe=liste>25
liste[sonListe]

array([68, 98, 37, 52, 73, 58, 57, 80, 73, 99, 89, 85, 57, 71, 99, 66, 56])

In [67]:
liste+liste # diğer işlemler de yapılabilir

array([136, 196,  34,  74, 104, 146, 116, 114,  36, 160, 146, 198, 178,
        32, 170, 114, 142, 198, 132, 112])

In [68]:
np.sqrt(liste)

array([8.24621125, 9.89949494, 4.12310563, 6.08276253, 7.21110255,
       8.54400375, 7.61577311, 7.54983444, 4.24264069, 8.94427191,
       8.54400375, 9.94987437, 9.43398113, 4.        , 9.21954446,
       7.54983444, 8.42614977, 9.94987437, 8.1240384 , 7.48331477])